---
sidebar: sidebar
permalink: concept-privacy.html
keywords: privacy, data privacy, credentials, access to credentials, hashicorp vault
summary: NetApp doesn't have access to any credentials that you provide while using NetApp Copy and Sync. The credentials are stored directly on the data broker machine, which resides in your network.
---

= Data privacy in NetApp Copy and Sync
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp doesn't have access to any credentials that you provide while using NetApp Copy and Sync. The credentials are stored directly on the data broker machine, which resides in your network.

Depending on the configuration that you choose, Copy and Sync might prompt you for credentials when you create a new relationship. For example, when setting up a relationship that includes an SMB server, or when deploying the data broker in AWS.

These credentials are always saved directly to the data broker itself. The data broker resides on a machine in your network, whether it's on premises or in your cloud account. The credentials are never made available to NetApp.

The credentials are locally encrypted on the data broker machine using HashiCorp Vault.
